version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - AI_SERVICE_URL=http://<THAY_IP_RUNPOD>:8000
    depends_on:
      - minio

  frontend:
    # Build React app sau
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
